In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import torch
import torch.nn as nn


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dell\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\dell\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\dell\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\dell\anaconda3\Lib\site-packages

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



In [2]:
df = pd.read_csv(r"C:\Users\dell\Desktop\MyDocs\Docs\MK\Income_Urban_VS_Rural.csv")
df

County        State   FIPS  State FIPS Code  \
0          Autauga County      Alabama   1001                1   
1          Baldwin County      Alabama   1003                1   
2          Barbour County      Alabama   1005                1   
3             Bibb County      Alabama   1007                1   
4           Blount County      Alabama   1009                1   
...                   ...          ...    ...              ...   
3217  Vega Baja Municipio  Puerto Rico  72145               72   
3218    Vieques Municipio  Puerto Rico  72147               72   
3219   Villalba Municipio  Puerto Rico  72149               72   
3220    Yabucoa Municipio  Puerto Rico  72151               72   
3221      Yauco Municipio  Puerto Rico  72153               72   

      County FIPS Code  Total Population  Median Household Income Urban-Rural  
0                    1             59285                    69841       Urban  
1                    3            239945                    75019       Urban  
2                    5             24757                    44290       Rural  
3                    7             22152                    51215       Rural  
4                    9             59292                    61096       Urban  
...                ...               ...                      ...         ...  
3217               145             54058                    23877       Urban  
3218               147              8147                    17531       Rural  
3219               149             21778                    24882       Rural  
3220               151             29868                    21279       Urban  
3221               153             33509                    21918       Urban  

[3222 rows x 8 columns]

In [3]:
len(df.columns)

8

In [4]:
df.County.value_counts()

County
Washington County     30
Jefferson County      25
Franklin County       24
Jackson County        23
Lincoln County        23
                      ..
Ponce Municipio        1
Peñuelas Municipio     1
Patillas Municipio     1
Orocovis Municipio     1
Chilton County         1
Name: count, Length: 1960, dtype: int64

In [5]:
category_columns = []
for i in df.columns:
  if df[i].dtype == object and i !="Urban-Rural":
    category_columns.append(i)

In [6]:
numerical_columns= []
for j in df.columns:
  if j not in category_columns and j!="Urban-Rural":
    numerical_columns.append(j)

In [7]:
arranged_columns = category_columns + numerical_columns + ["Urban-Rural"]

In [8]:
df = df[arranged_columns]

In [9]:
len(df.columns)

8

In [10]:
df.State.value_counts()

State
Texas                   254
Georgia                 159
Virginia                133
Kentucky                120
Missouri                115
Kansas                  105
Illinois                102
North Carolina          100
Iowa                     99
Tennessee                95
Nebraska                 93
Indiana                  92
Ohio                     88
Minnesota                87
Michigan                 83
Mississippi              82
Puerto Rico              78
Oklahoma                 77
Arkansas                 75
Wisconsin                72
Alabama                  67
Pennsylvania             67
Florida                  67
South Dakota             66
Colorado                 64
Louisiana                64
New York                 62
California               58
Montana                  56
West Virginia            55
North Dakota             53
South Carolina           46
Idaho                    44
Washington               39
Oregon                   36
New Mexico    

In [11]:
df.isna().sum()

County                     0
State                      0
FIPS                       0
State FIPS Code            0
County FIPS Code           0
Total Population           0
Median Household Income    0
Urban-Rural                0
dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df.iloc[: , 2:7]= sc.fit_transform(df.iloc[: , 2:7])

C:\Users\dell\AppData\Local\Temp\ipykernel_7456\3027607212.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.86395384 -1.86383112 -1.86370839 ...  2.50175265  2.50187537
  2.50199809]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[: , 2:7]= sc.fit_transform(df.iloc[: , 2:7])
C:\Users\dell\AppData\Local\Temp\ipykernel_7456\3027607212.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.85933395 -1.85933395 -1.85933395 ...  2.50116585  2.50116585
  2.50116585]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[: , 2:7]= sc.fit_transform(df.iloc[: , 2:7])
C:\Users\dell\AppData\Local\Temp\ipykernel_7456\3027607212.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.959

In [13]:
df

County        State      FIPS  State FIPS Code  \
0          Autauga County      Alabama -1.863954        -1.859334   
1          Baldwin County      Alabama -1.863831        -1.859334   
2          Barbour County      Alabama -1.863708        -1.859334   
3             Bibb County      Alabama -1.863586        -1.859334   
4           Blount County      Alabama -1.863463        -1.859334   
...                   ...          ...       ...              ...   
3217  Vega Baja Municipio  Puerto Rico  2.501507         2.501166   
3218    Vieques Municipio  Puerto Rico  2.501630         2.501166   
3219   Villalba Municipio  Puerto Rico  2.501753         2.501166   
3220    Yabucoa Municipio  Puerto Rico  2.501875         2.501166   
3221      Yauco Municipio  Puerto Rico  2.501998         2.501166   

      County FIPS Code  Total Population  Median Household Income Urban-Rural  
0            -0.959379         -0.136179                 0.025211       Urban  
1            -0.940607          0.411910                 0.025523       Urban  
2            -0.921836         -0.240931                 0.023672       Rural  
3            -0.903064         -0.248834                 0.024089       Rural  
4            -0.884293         -0.136158                 0.024684       Urban  
...                ...               ...                      ...         ...  
3217          0.392172         -0.152037                 0.022443       Urban  
3218          0.410943         -0.291323                 0.022061       Rural  
3219          0.429715         -0.249969                 0.022504       Rural  
3220          0.448487         -0.225425                 0.022287       Urban  
3221          0.467258         -0.214379                 0.022325       Urban  

[3222 rows x 8 columns]

In [14]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [15]:
len(X[0])

7

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1])], remainder='passthrough')
X = ct.fit_transform(X).toarray()

In [17]:
X[0]

array([ 0.        ,  0.        ,  0.        , ..., -0.95937887,
       -0.13617918,  0.02521093])

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
y

array([1, 1, 0, ..., 0, 1, 1])

In [20]:
class SimpleClassificationModel(nn.Module):
  def __init__(self, in_features, out_features):
    super().__init__()
    self.layer = nn.Sequential(
        nn.Linear(in_features = in_features, out_features = 120),
        nn.ReLU(),
        nn.Linear(in_features = 120, out_features =240),
        nn.ReLU(),
        nn.Linear(in_features =240 ,out_features =1)
    )
  def forward(self , x):
    return self.layer(x)

In [21]:
in_features = X.shape[1]
out_features = 1

In [22]:
in_features

2017

In [23]:
model1 = SimpleClassificationModel(in_features , out_features)

In [24]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(params = model1.parameters(), lr = 0.01)

In [25]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [26]:
X_train_tensor = torch.tensor(X_train , dtype = torch.float32)
y_train_tensor = torch.tensor(y_train , dtype = torch.float32)
X_test_tensor = torch.tensor(X_test , dtype = torch.float32)
y_test_tensor = torch.tensor(y_test , dtype = torch.float32)

In [27]:
epochs =15000
for epoch in range(epochs):
  model1.train()
  y_pred = model1(X_train_tensor).squeeze()
  loss = loss_fn(y_pred , y_train_tensor)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model1.eval()
  with torch.no_grad():
    y_pred = model1(X_test_tensor).squeeze()
    test_loss = loss_fn(y_pred , y_test_tensor)
    if epoch%10==0:
      print(f" epoch :{ epoch }----> train loss : {loss} || test loss : {test_loss}")

 epoch :0----> train loss : 0.6930719614028931 || test loss : 0.6929395198822021
 epoch :10----> train loss : 0.693014919757843 || test loss : 0.6928939819335938
 epoch :20----> train loss : 0.6929582953453064 || test loss : 0.6928486824035645
 epoch :30----> train loss : 0.6929022669792175 || test loss : 0.6928033828735352
 epoch :40----> train loss : 0.6928468346595764 || test loss : 0.692758321762085
 epoch :50----> train loss : 0.6927915811538696 || test loss : 0.6927131414413452
 epoch :60----> train loss : 0.6927366852760315 || test loss : 0.692668080329895
 epoch :70----> train loss : 0.6926820874214172 || test loss : 0.6926227807998657
 epoch :80----> train loss : 0.6926277279853821 || test loss : 0.6925774812698364
 epoch :90----> train loss : 0.6925733089447021 || test loss : 0.6925317049026489
 epoch :100----> train loss : 0.6925190687179565 || test loss : 0.6924857497215271
 epoch :110----> train loss : 0.6924648284912109 || test loss : 0.692439615726471
 epoch :120----> tr

In [28]:
model1.eval()
with torch.inference_mode():
  y_pred_logits = model1(X_test_tensor).squeeze()
  y_pred_prob = torch.sigmoid(y_pred_logits)
  y_pred_label = torch.round(y_pred_prob)

In [29]:
y_pred_label= y_pred_label.numpy()

In [30]:
y_pred_label

array([0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 0.

In [31]:
from sklearn.metrics import accuracy_score
score  = accuracy_score(y_test , y_pred_label)
print(f"accuracy : {score*100} %")

accuracy : 95.96899224806201 %
